import type { Question } from '../../types'

const q = (
  id: string,
  prompt: string,
  choices: string[],
  answerIndex: number,
  explanation: string,
): Question => ({ id, prompt, choices, answerIndex, explanation })

export const day1: Question[] = [
  q('d1-01', 'DDL 主要負責什麼？', ['定義或修改資料表結構', '只負責插入列', '只負責授權帳號', '只負責備份檔案'], 0, 'CREATE／ALTER／DROP 屬於 DDL。'),
  q('d1-02', '下列何者是典型的 CRUD 讀取操作？', ['SELECT', 'CREATE TABLE', 'GRANT', '備份指令'], 0, 'Read 對應 SELECT。'),
  q('d1-03', '資料表的 PK 通常用來做什麼？', ['唯一識別每一列', '儲存多個聯絡方式在同一欄', '取代所有查詢條件', '禁止任何 INSERT'], 0, 'PK 識別列。'),
  q('d1-04', '某欄加上 UNIQUE 約束代表？', ['不同列不能有相同值', '該欄必須當 PK', '該欄會自動轉大寫', '該欄不能出現在 WHERE'], 0, 'UNIQUE 禁止重複。'),
  q('d1-05', '商品價格用精確小數型別較適合的原因？', ['金錢需要精確小數，避免浮點誤差', '一定比整數查詢快', '價格欄不能存小數', '會自動計算稅額'], 0, '金額宜用精確數值型別。'),
  q('d1-06', 'INSERT INTO users (name, email) VALUES (...) 屬於？', ['DML', 'DDL', '只屬於備份語言', '作業系統指令'], 0, 'INSERT 是資料操作。'),
  q('d1-07', 'UPDATE products SET price = 4000 沒有 WHERE 會怎樣？', ['可能改到所有商品列', '只改第一列', '語法一定失敗', '只改 PK 最小的那列'], 0, '缺少 WHERE 會更新全表。'),
  q('d1-08', 'DELETE FROM products WHERE id = 9 會？', ['刪除符合條件的列（若存在）', '刪除整張表的結構', '只把價格改成 NULL', '自動改名索引'], 0, 'DELETE 刪列，DROP 才刪結構。'),
  q('d1-09', 'SELECT * FROM 某表 裡的 * 代表什麼？', ['該表所有欄位', '只選 PK', '只選非空欄', '隨機一欄'], 0, '* 展開全部欄。'),
  q('d1-10', 'FK 欄位的作用是什麼？', ['指向另一張表的 PK（或唯一鍵），表達關聯', '讓兩張表必須同名', '禁止 JOIN', '自動合併兩張表'], 0, '參照完整性。'),
  q('d1-11', '時間戳欄位適合記錄？', ['列被建立或更新的時間', '資料庫產品名稱', 'FK目標表名', '索引選擇性百分比'], 0, '記錄時間。'),
  q('d1-12', '整數 PK 設為自動遞增，常見效果是什麼？', ['插入時可省略 id，由系統產生', '自動產生 UUID 字串', '禁止 INSERT', '把欄位變成陣列'], 0, '代理鍵常見作法。'),
  q('d1-13', '篩選城市等於指定值的使用者，正確寫法是？', ["SELECT * FROM users WHERE city = 'Taipei'", 'SELECT * FROM users WHERE Taipei', "SELECT * FROM users WHERE city = Taipei", 'DELETE FROM users WHERE city'], 0, '字串常數需用單引號，並寫在 WHERE 欄位比較中。'),
  q('d1-14', 'CRUD 的 U 是指？', ['UPDATE', 'UNION', 'UNIQUE', 'DROP'], 0, 'Update。'),
  q('d1-15', 'CREATE DATABASE（建立資料庫）主要屬於哪類工作？', ['結構／管理工作（常歸 DDL 或管理指令）', '單純 SELECT', '只能透過網頁表單完成', '違反第一正規化'], 0, '建立庫是結構工作。'),
  q('d1-16', '整數欄宣告 DEFAULT 0 表示什麼？', ['插入未指定時用 0', '該欄永遠不能改', '該欄必須是負數', '該欄成為 PK'], 0, '預設值。'),
  q('d1-17', '練習 SQL 時親手輸入的主要好處？', ['加深語法記憶與除錯能力', '伺服器會拒絕複製貼上', '不親手輸入表就會消失', 'JOIN 會自動失效'], 0, '刻意練習。'),
  q('d1-18', '「一分類對多商品」在關聯上通常怎麼做？', ['商品表放分類 FK', '商品名稱欄塞入多個分類', '禁止 FK', '兩表不需要鍵'], 0, '多方放 FK。'),
  q('d1-19', '可變長度字串型別（有長度上限）表示？', ['儲存文字，長度不超過宣告上限', '一定補滿空白到上限', '只能存數字', '等同布林值'], 0, 'VARCHAR 一類。'),
  q('d1-20', '用 PK 等值條件查出一列，這是在做什麼？', ['以鍵查找單筆', '刪除該列', '建立新表', '建立索引'], 0, '點查。'),
  q('d1-21', 'NOT NULL 約束的意義？', ['插入／更新時該欄必須有值', '該欄永遠不能 UPDATE', '該欄一定是FK', '該欄自動唯一'], 0, '禁止空值。'),
]

export const day2: Question[] = [
  q('d2-01', '找出價格介於 1000 與 3000 的商品，適合？', ['WHERE price BETWEEN 1000 AND 3000', 'WHERE price IN (1000)', 'GROUP BY price', 'HAVING price'], 0, 'BETWEEN 做閉區間。'),
  q('d2-02', '要找商品名稱含 helmet 的列，WHERE 怎麼寫較適合？', ["WHERE name LIKE '%helmet%'", "WHERE name = 'helmet'", 'WHERE name LIKE helmet', 'ORDER BY helmet'], 0, "LIKE 模式字串要用單引號，前後 % 表示子字串。"),
  q('d2-03', '要把商品依價格由高到低排列，應寫？', ['ORDER BY price DESC', 'ORDER BY price ASC', 'GROUP BY price DESC', 'LIMIT price'], 0, 'DESC 由大到小。'),
  q('d2-04', '只要價格最高的前 3 筆商品，應寫？', ['ORDER BY price DESC LIMIT 3', 'LIMIT 3', 'WHERE LIMIT 3', 'HAVING LIMIT 3'], 0, '排序後再 LIMIT。'),
  q('d2-05', '要統計 products 有幾列，應寫？', ['SELECT COUNT(*) FROM products', 'SELECT SUM(*) FROM products', 'SELECT MAX(*) FROM products', 'SELECT products++'], 0, 'COUNT(*)。'),
  q('d2-06', '要算全部商品的平均價格，應寫？', ['SELECT AVG(price) FROM products', 'SELECT MEAN FROM products', 'SELECT COUNT(price) / price FROM products', 'SELECT price AVERAGE FROM products'], 0, 'AVG。'),
  q('d2-07', "WHERE city IN ('Taipei', 'Taoyuan') 會？", ['找出城市為這兩個值之一的列', '排除這兩個值', '只找第一個值', '語法無效'], 0, 'IN 列出允許值，字串用單引號。'),
  q('d2-08', 'price <> 4200 表示？', ['價格不等於 4200', '價格必須等於 4200', '價格為 NULL', '價格介於 0 與 4200'], 0, '不等於。'),
  q('d2-09', '要統計 2024-01-01 當天新增的使用者人數，較完整的寫法是？', ["SELECT COUNT(*) FROM users WHERE created_at >= '2024-01-01' AND created_at < '2024-01-02'", 'GROUP BY email', 'DELETE FROM users', 'LIMIT 1'], 0, '先用 WHERE 限制日期再 COUNT(*)；日期字串用單引號。'),
  q('d2-10', 'MIN(price) 會得到什麼？', ['最低價格', '最長商品名', '隨機一列', 'PK 最小值'], 0, 'MIN。'),
  q('d2-11', 'MAX(stock) 會得到？', ['最大庫存值', '最多訂單數', '最晚建立時間', '分類名稱'], 0, 'MAX。'),
  q('d2-12', 'SUM(stock) 適合描述？', ['庫存加總', '平均庫存', '不重複庫存種數', '庫存中位數'], 0, 'SUM。'),
  q('d2-13', "LIKE 'A%' 與 LIKE '%A' 差在哪？", ['前者比對開頭、後者比對結尾', '完全相同', '都只能配數字', '兩者都是語法錯誤'], 0, '萬用字元位置。'),
  q('d2-14', 'ORDER BY city, name 的排序優先順序是？', ['先依 city，相同時再依 name', '只依 name', '先依 name 再依 city', '忽略 city'], 0, '左到右優先。'),
  q('d2-15', '沒有 ORDER BY、只寫 LIMIT 3，結果會怎樣？', ['不保證是最貴或最新的 3 筆', '一定是 PK 前 3 筆', '一定可重現的隨機', '語法禁止'], 0, '無排序則順序未定義。'),
  q('d2-16', '同一句既有 WHERE 又有聚合函數、但沒有 GROUP BY 時，執行順序是？', ['先用 WHERE 過濾列再對剩餘列聚合', '必須寫 HAVING', 'WHERE 不能與 AVG 同句', '只能拆成兩條 SQL'], 0, 'WHERE 在聚合前。'),
  q('d2-17', '要列出某個分類（例如 category_id = 2）的商品，應寫？', ['WHERE category_id = 2', "WHERE name = '2'", 'HAVING category_id = 2', 'ORDER BY 2'], 0, '等值過濾 FK。'),
  q('d2-18', 'BETWEEN 800 AND 1000 對端點的常見語意？', ['通常包含 800 與 1000', '永遠排除端點', '只含 800', '語法錯誤'], 0, '閉區間。'),
  q('d2-19', 'COUNT(city) 與 COUNT(*) 可能不同是因為？', ['COUNT(city) 忽略 city 為 NULL 的列', 'COUNT(*) 忽略全部列', '兩者永遠相同', 'COUNT(city) 會把字串加總'], 0, 'COUNT 欄不計 NULL。'),
  q('d2-20', '只要價格高於 5000 的商品，應寫？', ['WHERE price > 5000', 'WHERE price < 5000', 'HAVING *', 'LIMIT 5000'], 0, '比較運算。'),
  q('d2-21', "只要 city = 'Taipei' 的列，並依建立時間由新到舊排，應寫？", ["WHERE city = 'Taipei' ORDER BY created_at DESC", 'ORDER BY created_at DESC WHERE city', "GROUP BY city = 'Taipei'", 'DELETE THEN SELECT'], 0, 'WHERE 過濾、ORDER BY 排序；字串用單引號。'),
]

export const day3: Question[] = [
  q('d3-01', '統計每位使用者訂單數，核心寫法是？', ['SELECT user_id, COUNT(*) FROM orders GROUP BY user_id', 'LIMIT user_id', 'UNION user_id', 'DROP user_id'], 0, '依 user_id 分組。'),
  q('d3-02', '要算每位使用者的訂單總金額，核心寫法是？', ['SELECT user_id, SUM(total_amount) FROM orders GROUP BY user_id', 'AVG 不能用在金額', 'COUNT(total_amount) 等於總金額', 'MAX 永遠等於 SUM'], 0, '分組加總。'),
  q('d3-03', 'HAVING SUM(total_amount) > 10000 適合在什麼時候用？', ['分組之後再篩選各組', '插入前篩選', '刪除表', '建立索引'], 0, 'HAVING 過濾組。'),
  q('d3-04', 'WHERE 與 HAVING 最大差別？', ['WHERE 在分組前過濾列，HAVING 在分組後', 'HAVING 可完全取代 WHERE', 'WHERE 只能寫聚合', '兩者語意完全相同'], 0, '階段不同。'),
  q('d3-05', 'SELECT user_id, COUNT(*) FROM orders 在嚴格模式下未寫 GROUP BY，通常會？', ['通常不合法（非聚合欄未分組）', '一定回傳一列', '自動對全部欄分組', '自動變成 JOIN'], 0, '非聚合欄要進 GROUP BY。'),
  q('d3-06', '依訂單狀態 GROUP BY，主要能做什麼？', ['統計各狀態的訂單數', '刪除狀態欄', '強制全表只剩一種狀態', '違反 1NF'], 0, '依狀態分組。'),
  q('d3-07', '找出訂單數 >= 2 的使用者？', ['SELECT user_id FROM orders GROUP BY user_id HAVING COUNT(*) >= 2', 'WHERE COUNT(*) >= 2', 'LIMIT 2', 'ORDER BY 2'], 0, '組後條件用 HAVING。'),
  q('d3-08', '先用 WHERE 限制訂單日期，再依使用者 GROUP BY，結果會？', ['先去掉不符合日期的訂單再分組', '先分組就無法再過濾日期', '忽略 WHERE', '等同 HAVING 日期'], 0, 'WHERE 先濾列。'),
  q('d3-09', '依使用者鍵 GROUP BY 之後，每一位使用者會變成？', ['其所有訂單彙總成一組', '每一筆訂單各成一組', '該使用者會從使用者表刪除', '信箱會變 PK'], 0, '同一鍵一組。'),
  q('d3-10', '在 PK 欄上 COUNT(*) 與 COUNT(PK) 通常差在哪？', ['結果相同（PK 非 NULL）', 'COUNT(*) 永遠為 0', 'COUNT(PK) 非法', '兩者必差 1'], 0, 'PK 非空。'),
  q('d3-11', 'AVG(金額) 並依使用者 GROUP BY，得到的是？', ['每位使用者的平均訂單金額', '全站唯一一個平均', '最大訂單', '商品均價'], 0, '每組平均。'),
  q('d3-12', 'HAVING 裡通常可以出現？', ['聚合表達式', '未分組的任意列值當組代表且保證正確', 'CREATE INDEX', 'INSERT'], 0, '組層級條件。'),
  q('d3-13', "想排除 status = 'pending' 的訂單再統計總額，條件應放哪？", ["WHERE status <> 'pending'", "HAVING status <> 'pending' 且無聚合", 'GROUP BY 無法與 WHERE 共存', "ORDER BY status = 'pending'"], 0, "列級用 WHERE；字串用單引號。"),
  q('d3-14', 'GROUP BY 使用者, 狀態 代表怎麼分組？', ['同一使用者不同狀態分成不同組', '只能選一個分組欄', '會產生笛卡兒積', '刪除 FK'], 0, '複合分組鍵。'),
  q('d3-15', '訂單表常見最小欄位包含？', ['訂單鍵、使用者FK、金額、時間', '必須把所有商品名塞進同一欄', '禁止FK', '必須是 CPK'], 0, '訂單實體。'),
  q('d3-16', '同一句 SELECT 能不能同時寫 SUM 與 COUNT？', ['可以，對同一組算不同聚合', '只能選一個聚合', '必須寫兩個 GROUP BY', '會鎖表'], 0, '一組多聚合。'),
  q('d3-17', 'HAVING COUNT(*) > 1 找的是？', ['組內超過一列的那些組', '價格大於 1 的商品', 'PK大於 1', '名稱長度'], 0, '組內列數。'),
  q('d3-18', '只寫 SELECT COUNT(*) FROM orders（沒有 GROUP BY）會得到？', ['全表訂單總數（一列）', '每位使用者一列', '必須加 HAVING', '錯誤因為沒依使用者分組'], 0, '無 GROUP BY 則整表一組。'),
  q('d3-19', "統計 status = 'paid' 的訂單總額？", ["SELECT SUM(total_amount) FROM orders WHERE status = 'paid'", "HAVING status = 'paid'", 'GROUP BY email', "SELECT * FROM users WHERE name LIKE 'paid'"], 0, '先 WHERE 再 SUM；字串用單引號。'),
  q('d3-20', '為什麼 HAVING 不能完全取代 WHERE？', ['列級條件應在分組前過濾，語意更清楚也常較有效率', 'HAVING 不能寫比較符號', 'WHERE 已廢棄', '索引只吃 HAVING'], 0, '階段不同。'),
  q('d3-21', 'JOIN 使用者表後依使用者 PK GROUP BY，通常還能一併 SELECT？', ['使用者屬性（如姓名）與訂單數', '任意未分組的訂單金額當「代表金額」且保證正確', '只能顯示 PK', '不能 SELECT 姓名'], 0, '依 PK 分組可選其決定的屬性。'),
]
