import type { Exercise, Lesson } from '../../types'

/**
 * 世界 1「一張表」：關 1、關 2。
 * expect 全部用實際跑 data/learning-db-seed.sql 得到的結果寫的（pglite 驗過）。
 */
export const world1: Record<number, Lesson[]> = {
  1: [
    {
      id: '1-1',
      title: '資料庫長什麼樣',
      focus: '認出「表、列、欄、PK」四個東西',
      check: '打開 users 表，指得出哪裡是列、哪裡是欄、哪欄是 PK',
      concept: '資料庫是檔案櫃，表是一張 Excel，一列是一筆資料，一欄是一種屬性。id 那欄是 PK。',
      explain: [
        'Database｜資料庫：一個檔案櫃。裡面有很多抽屜（表）。',
        'Table｜表：一張 Excel。users 表就是「所有使用者」那張。',
        'Row｜列：橫的一條 = 一個人（Alice 那一列）。Column｜欄：直的一條 = 一種屬性（name、email）。',
        'Primary Key｜主鍵：每一列的身分證字號，絕不重複。users 的 id 欄就是。',
        '怎麼畫：畫一張 3×3 的表格，橫向寫「列」，直向寫「欄」，左上角的 id 圈起來寫 PK。',
      ],
      cards: [6, 7, 1],
      exercises: [
        {
          task: '在 psql 打：\\d users   （反斜線 d，看 users 表的結構）。數一數有幾欄、欄名各是什麼。',
          hint: '\\d 是 psql 自己的指令（不是 SQL），結尾不用分號。',
          expect: '5 欄：id、name、email、city、created_at。最下面 Indexes 那段會看到 users_pkey → id 是 PK。',
          answer: '\\d users',
          pitfalls: ['打成 /d（斜線方向錯）會沒反應。是反斜線 \\，在 Enter 上面那顆。'],
        },
        {
          task: 'SELECT * FROM users;   看全部的人。數一數有幾列。',
          hint: '* 代表「全部的欄」。結尾一定要有分號 ;',
          expect: '10 列。第一列 id=1 Alice Chen（Taoyuan），最後一列 id=10 Jack Peng（Taichung）。最下面會顯示 (10 rows)。',
          answer: 'SELECT * FROM users;',
          pitfalls: ['沒打分號會看到提示符號變成 learning_db-#（減號），代表它還在等你。補一個 ; 再 Enter 就好。'],
        },
        {
          task: 'SELECT * FROM products;   用眼睛找出最貴的商品叫什麼。',
          hint: '看 price 那一欄，找最大的數字。',
          expect: '10 列。最貴的是 Modular Helmet M2，價格 6800.00。',
          answer: 'SELECT * FROM products;   → Modular Helmet M2（6800.00）',
        },
      ],
      project: {
        task: '在筆記本畫一張「飼主 owners」表：你覺得需要哪些欄？至少 4 欄，圈出哪一欄是 PK。',
        hint: '想「要記飼主的什麼」：名字？聯絡方式？住哪？再加一個 id 當身分證。',
        expect: '一張表格，第一欄是 id 且被圈起來寫 PK；其他至少 3 欄（例如 name、email、phone、city）。',
        answer: 'owners(id PK, name, email, phone, city)。任何合理的 4 欄都算對，重點是 id 被標成 PK。',
      },
      teachKeys: ['表 = 一張 Excel', '列 = 一筆資料、欄 = 一種屬性', 'PK 是每一列不重複的身分證'],
    },
    {
      id: '1-2',
      title: 'SELECT 與 WHERE',
      focus: '用 SELECT 挑欄、用 WHERE 挑列',
      check: '寫出一句有 WHERE 的 SELECT，跑出你想要的那幾列',
      concept: 'SELECT 決定「看哪幾欄」，WHERE 決定「留哪幾列」。',
      explain: [
        'SELECT … FROM …｜從哪張表拿哪些欄：SELECT 後面列欄名（直的），FROM 後面寫表名。',
        'WHERE｜篩選條件：只留下符合條件的列（橫的）。沒有 WHERE = 全部都給你。',
        '比喻：SELECT 是決定「要看哪幾直排」，WHERE 是「用漏斗把橫排濾掉一些」。',
        '文字要用單引號 \'Taipei\'，數字不用引號 3000。',
        '怎麼畫：畫一張表，把要的直排塗色（SELECT），再把不要的橫排劃掉（WHERE）。',
      ],
      cards: [9, 10],
      exercises: [
        {
          task: 'SELECT name, email FROM users;',
          hint: '兩個欄名中間用逗號。',
          expect: '10 列、只有 2 欄（name、email）。第一列 Alice Chen | alice@example.com。',
          answer: 'SELECT name, email FROM users;',
          pitfalls: ['欄名之間漏逗號 → syntax error at or near "email"。'],
        },
        {
          task: "SELECT * FROM users WHERE city = 'Taipei';",
          hint: '文字要包單引號，大小寫要一樣（Taipei 不是 taipei）。',
          expect: '2 列：Bob Lin（id 2）、Henry Kuo（id 8）。',
          answer: "SELECT * FROM users WHERE city = 'Taipei';",
          pitfalls: ['用雙引號 "Taipei" → column "Taipei" does not exist。雙引號是給欄名用的，文字值要單引號。'],
        },
        {
          task: 'SELECT name, price FROM products WHERE price > 3000;',
          hint: '數字不用引號。> 是「大於」。',
          expect: '6 列：Full Face Helmet A1（4200）、Modular Helmet M2（6800）、Bluetooth Headset B1（3200）、Mesh Intercom X2（5900）、Riding Jacket J1（4500）、Summer Jacket J2（3600）。',
          answer: 'SELECT name, price FROM products WHERE price > 3000;',
        },
      ],
      project: {
        task: "假設有 pets 表（欄：id, name, species, owner_id）。寫一句「找出所有狗」的 SQL（species = 'dog'）。先寫在筆記本。",
        hint: '照 SELECT … FROM pets WHERE … 的格子填：表名 pets，條件 species = \'dog\'。',
        expect: "一句 SQL，有 FROM pets、有 WHERE species = 'dog'、結尾分號。",
        answer: "SELECT * FROM pets WHERE species = 'dog';",
      },
      teachKeys: ['SELECT 挑欄（直的）', 'WHERE 挑列（橫的）', '文字用單引號'],
    },
    {
      id: '1-3',
      title: 'INSERT／UPDATE／DELETE',
      focus: '新增、修改、刪除一列，而且 UPDATE／DELETE 一定帶 WHERE',
      check: '自己 INSERT 一筆、UPDATE 它、再 DELETE 它，表沒被弄壞',
      concept: '新增、修改、刪除。UPDATE 和 DELETE 一定要有 WHERE，否則整張表都會被改／刪。',
      explain: [
        'CRUD｜新增／讀取／修改／刪除 = INSERT／SELECT／UPDATE／DELETE，資料的四個基本動作。',
        'INSERT INTO 表 (欄, 欄) VALUES (值, 值);｜新增一列。欄和值一一對應，id 不用填（SERIAL 會自己長）。',
        'UPDATE 表 SET 欄 = 值 WHERE 條件;｜改。DELETE FROM 表 WHERE 條件;｜刪。',
        '⚠ 鐵律：UPDATE／DELETE 先寫 WHERE 再寫前面。沒有 WHERE = 整張表。',
        '每做一個動作就 SELECT 一次確認，這是好習慣。',
      ],
      cards: [8, 11, 12, 13],
      exercises: [
        {
          task: "INSERT INTO users (name, email, city) VALUES ('Sasha', 'sasha@example.com', 'Taipei');   然後 SELECT * FROM users WHERE name = 'Sasha';",
          hint: '欄名 3 個、值 3 個，順序一樣。',
          expect: '第一句回 INSERT 0 1（成功 1 列）。第二句 1 列：id 是 11（自動長的）、Sasha、sasha@example.com、Taipei。',
          answer: "INSERT INTO users (name, email, city) VALUES ('Sasha', 'sasha@example.com', 'Taipei');",
          pitfalls: ['email 重複會報 duplicate key value violates unique constraint → 換一個 email。'],
        },
        {
          task: 'UPDATE products SET price = 3999 WHERE id = 1;   然後 SELECT name, price FROM products WHERE id = 1;',
          hint: 'SET 寫「改成什麼」，WHERE 寫「改哪一列」。',
          expect: '第一句回 UPDATE 1。第二句 1 列：Full Face Helmet A1 | 3999.00。（做完可以改回 4200：UPDATE products SET price = 4200 WHERE id = 1;）',
          answer: 'UPDATE products SET price = 3999 WHERE id = 1;',
          pitfalls: ['回 UPDATE 10 而不是 UPDATE 1 → 你忘了 WHERE，全表都被改了。重新匯入 seed 就能救回。'],
        },
        {
          task: "DELETE FROM users WHERE email = 'sasha@example.com';   然後 SELECT * FROM users WHERE name = 'Sasha';",
          hint: '先在腦中念一次「刪掉 email 是 sasha 的那列」，再打。',
          expect: '第一句回 DELETE 1。第二句 (0 rows)，Sasha 不見了；users 回到 10 列。',
          answer: "DELETE FROM users WHERE email = 'sasha@example.com';",
          pitfalls: ['DELETE 10 → 沒 WHERE，全刪了。重新匯入 seed（關 0 第 5 步的指令）。'],
        },
      ],
      project: {
        task: '寫一句 INSERT，把你的（或想像中的）寵物放進 pets 表（欄：name, species, owner_id）。',
        hint: '照 INSERT INTO pets (name, species, owner_id) VALUES (…) 填。owner_id 是數字，不加引號。',
        expect: '欄 3 個、值 3 個；文字有單引號，owner_id 沒有。',
        answer: "INSERT INTO pets (name, species, owner_id) VALUES ('豆豆', 'dog', 1);",
      },
      teachKeys: ['INSERT 新增、UPDATE 改、DELETE 刪', 'UPDATE／DELETE 一定要 WHERE', '做完 SELECT 確認'],
    },
    {
      id: '1-4',
      title: 'CREATE TABLE：自己蓋一張表',
      focus: '自己蓋一張表（CREATE TABLE）',
      check: '寫出一張 pets 表，INSERT 兩筆，SELECT 得出來',
      concept: 'DDL 是蓋房子。CREATE TABLE 宣告表名、欄名、型別、約束。SERIAL 讓 id 自己長。',
      explain: [
        'DDL vs DML｜蓋房子 vs 搬家具：CREATE／ALTER／DROP 是改結構；INSERT／SELECT／UPDATE／DELETE 是動資料。',
        'CREATE TABLE 表名 ( 欄名 型別 約束, … );｜每一欄一行，逗號分開，最後一欄不加逗號。',
        'Data type｜型別：SERIAL 自動編號、VARCHAR(50) 最多 50 字、INTEGER 整數、NUMERIC(10,2) 小數、DATE 日期。',
        'Constraint｜約束：PRIMARY KEY、NOT NULL（不能空）、UNIQUE（不能重複）、DEFAULT（沒填就用這個）。',
        '怎麼畫：畫一個房子，牆上寫欄名和型別；門牌是 id SERIAL PRIMARY KEY。',
      ],
      cards: [14, 15, 16, 17, 18],
      exercises: [
        {
          task: '打開 data/learning-db-seed.sql，看 CREATE TABLE users 那一段，逐欄說出型別是什麼。',
          hint: '每一行的第二個字就是型別。',
          expect: 'id SERIAL、name VARCHAR(100)、email VARCHAR(150) 且 UNIQUE、city VARCHAR(100)、created_at TIMESTAMP 且有 DEFAULT。',
          answer: 'id SERIAL PRIMARY KEY / name VARCHAR(100) NOT NULL / email VARCHAR(150) NOT NULL UNIQUE / city VARCHAR(100) / created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP',
        },
        {
          task: 'CREATE TABLE pets (id SERIAL PRIMARY KEY, name VARCHAR(50) NOT NULL, species VARCHAR(20) NOT NULL, birth_date DATE);',
          hint: '括號要成對，欄與欄之間逗號，最後一欄後面沒逗號。',
          expect: '回 CREATE TABLE。然後 \\d pets 會看到 4 欄。',
          answer: 'CREATE TABLE pets (id SERIAL PRIMARY KEY, name VARCHAR(50) NOT NULL, species VARCHAR(20) NOT NULL, birth_date DATE);',
          pitfalls: ['relation "pets" already exists → 之前建過了。DROP TABLE pets; 再建一次。', 'syntax error at end of input → 括號沒關或少分號。'],
        },
        {
          task: "INSERT INTO pets (name, species, birth_date) VALUES ('豆豆', 'dog', '2022-03-01'), ('咪咪', 'cat', '2023-07-15');   然後 SELECT * FROM pets;",
          hint: '一次插兩筆：兩組括號用逗號隔開。日期用單引號 \'YYYY-MM-DD\'。',
          expect: 'INSERT 0 2。SELECT 出 2 列：id 1 豆豆 dog 2022-03-01、id 2 咪咪 cat 2023-07-15。',
          answer: "INSERT INTO pets (name, species, birth_date) VALUES ('豆豆', 'dog', '2022-03-01'), ('咪咪', 'cat', '2023-07-15');",
        },
      ],
      project: {
        task: '恭喜：pets 就是你 side project 的第一張表。把它的 CREATE TABLE 抄進筆記本「我的專案」頁，並加一欄 owner_id INTEGER。',
        hint: '在 birth_date 後面加逗號，再加一行 owner_id INTEGER。',
        expect: '筆記本上一段完整的 CREATE TABLE pets，有 5 欄，id 是 SERIAL PRIMARY KEY。',
        answer: 'CREATE TABLE pets (id SERIAL PRIMARY KEY, name VARCHAR(50) NOT NULL, species VARCHAR(20) NOT NULL, birth_date DATE, owner_id INTEGER);',
      },
      teachKeys: ['CREATE TABLE 是 DDL（蓋房子）', '每欄有名字＋型別（＋約束）', 'SERIAL PRIMARY KEY 讓 id 自己長'],
    },
  ],
  2: [
    {
      id: '2-1',
      title: '比較運算子與 LIKE',
      focus: 'WHERE 裡除了 = 還有 IN／BETWEEN／LIKE',
      check: '用 LIKE 找出名字含某個字的商品',
      concept: 'WHERE 不只有 =。IN 是名單、BETWEEN 是範圍、LIKE 是模糊比對（% 任意字）。',
      explain: [
        'Comparison operators｜比較運算子：= <> > < >= <=，還有三個好用的：',
        "IN ('A', 'B')｜在名單裡：等於「= A 或 = B」。",
        'BETWEEN 2000 AND 5000｜在範圍內：含頭含尾。',
        "LIKE '%Helmet%'｜模糊比對：% 代表「任意長度的任何字」。'%Helmet%' = 中間有 Helmet 就算。",
        '怎麼畫：三個漏斗，分別寫「名單」「範圍」「含有」。',
      ],
      cards: [19, 20],
      exercises: [
        {
          task: "SELECT name, city FROM users WHERE city IN ('Taipei', 'Taoyuan');",
          hint: 'IN 後面是括號，裡面用逗號分開，每個文字都要單引號。',
          expect: '4 列：Alice Chen（Taoyuan）、Bob Lin（Taipei）、Grace Tsai（Taoyuan）、Henry Kuo（Taipei）。',
          answer: "SELECT name, city FROM users WHERE city IN ('Taipei', 'Taoyuan');",
        },
        {
          task: 'SELECT name, price FROM products WHERE price BETWEEN 2000 AND 5000;',
          hint: 'BETWEEN 小 AND 大，含 2000 和 5000。',
          expect: '5 列：Full Face Helmet A1（4200）、Open Face Helmet O3（2500）、Bluetooth Headset B1（3200）、Riding Jacket J1（4500）、Summer Jacket J2（3600）。',
          answer: 'SELECT name, price FROM products WHERE price BETWEEN 2000 AND 5000;',
        },
        {
          task: "SELECT name FROM products WHERE name LIKE '%Helmet%';",
          hint: '兩邊都有 %，代表前面後面有什麼都行。',
          expect: '3 列：Full Face Helmet A1、Modular Helmet M2、Open Face Helmet O3。',
          answer: "SELECT name FROM products WHERE name LIKE '%Helmet%';",
          pitfalls: ["LIKE 'Helmet' 沒有 % → 0 列，因為要「整個名字剛好等於 Helmet」。", 'LIKE 大小寫有差；不分大小寫用 ILIKE（PostgreSQL 專有）。'],
        },
      ],
      project: {
        task: "假設 foods 表有 name 欄。寫一句找出名字含「雞」的飼料。",
        hint: "LIKE '%雞%'，中文也一樣用 %。",
        expect: "一句 SQL：FROM foods、WHERE name LIKE '%雞%'。",
        answer: "SELECT * FROM foods WHERE name LIKE '%雞%';",
      },
      teachKeys: ['IN 是名單', 'BETWEEN 是範圍（含頭尾）', 'LIKE 配 % 是含有'],
    },
    {
      id: '2-2',
      title: 'ORDER BY 與 LIMIT',
      focus: '先排序（ORDER BY），再取前幾筆（LIMIT）',
      check: '查出最貴的 3 個商品',
      concept: '先排序，再取前幾筆。DESC 由大到小。',
      explain: [
        'ORDER BY 欄 ASC｜小到大（預設，可不寫）。ORDER BY 欄 DESC｜大到小。',
        '可以多欄：ORDER BY category_id, price DESC = 先照分類，同分類再照價格大到小。',
        'LIMIT 3｜只拿前 3 筆。一定配 ORDER BY 用，否則「前 3 筆」沒有意義。',
        '順序固定：… WHERE … ORDER BY … LIMIT …（WHERE 在前、LIMIT 一定最後）。',
        '怎麼畫：一疊卡片先排好（ORDER BY），再從上面拿 3 張（LIMIT）。',
      ],
      cards: [21, 22],
      exercises: [
        {
          task: 'SELECT name, price FROM products ORDER BY price DESC;',
          hint: 'DESC = descending = 由大到小。',
          expect: '10 列，第一列 Modular Helmet M2 6800.00，最後一列 Rain Gloves G2 900.00。',
          answer: 'SELECT name, price FROM products ORDER BY price DESC;',
        },
        {
          task: 'SELECT name, category_id, price FROM products ORDER BY category_id, price DESC;',
          hint: '兩個排序條件用逗號分開；DESC 只管它前面那一欄。',
          expect: '10 列。category_id 1 的三個在最前面且價格由大到小（6800、4200、2500），接著 category 2（5900、3200、1800）、3、4。',
          answer: 'SELECT name, category_id, price FROM products ORDER BY category_id, price DESC;',
        },
        {
          task: 'SELECT name, price FROM products ORDER BY price DESC LIMIT 3;',
          hint: 'LIMIT 放最後。',
          expect: '3 列：Modular Helmet M2（6800）、Mesh Intercom X2（5900）、Riding Jacket J1（4500）。',
          answer: 'SELECT name, price FROM products ORDER BY price DESC LIMIT 3;',
          pitfalls: ['LIMIT 寫在 ORDER BY 前面 → syntax error at or near "ORDER"。'],
        },
      ],
      project: {
        task: '假設 weight_logs 表有 pet_id, weight_kg, measured_at。寫一句「pet_id = 1 這隻寵物最新 5 筆體重」。',
        hint: '「最新」= measured_at 由大到小；「5 筆」= LIMIT 5；「這隻」= WHERE pet_id = 1。',
        expect: '一句 SQL，順序是 WHERE → ORDER BY measured_at DESC → LIMIT 5。',
        answer: 'SELECT weight_kg, measured_at FROM weight_logs WHERE pet_id = 1 ORDER BY measured_at DESC LIMIT 5;',
      },
      teachKeys: ['ORDER BY 排序、DESC 大到小', 'LIMIT 取前幾筆', 'LIMIT 一定放最後'],
    },
    {
      id: '2-3',
      title: '聚合函數',
      focus: '用 COUNT／AVG／MIN／MAX 把很多列算成一個數字',
      check: '算出商品的平均價和最高價',
      concept: 'COUNT／SUM／AVG／MIN／MAX 把很多列算成一個數字。NULL 不會被算進去。',
      explain: [
        'Aggregate functions｜聚合函數：把「很多列」壓成「一個數字」。',
        'COUNT(*) 幾列、SUM(欄) 加總、AVG(欄) 平均、MIN(欄) 最小、MAX(欄) 最大。',
        'NULL｜沒有值：不是 0、不是空字串。AVG 會直接跳過 NULL 不算。判斷用 IS NULL，不能用 = NULL。',
        '可以配 WHERE：先濾掉不要的列，再算。',
        '怎麼畫：很多列進漏斗，底下只掉出一個數字。',
      ],
      cards: [23, 24],
      exercises: [
        {
          task: 'SELECT COUNT(*) FROM users;',
          hint: 'COUNT(*) 數「有幾列」。',
          expect: '1 列 1 欄：count = 10。',
          answer: 'SELECT COUNT(*) FROM users;',
        },
        {
          task: 'SELECT AVG(price), MIN(price), MAX(price) FROM products;',
          hint: '三個函數用逗號分開，都放在 SELECT 後面。',
          expect: '1 列：avg = 3460.0000…、min = 900.00、max = 6800.00。',
          answer: 'SELECT AVG(price), MIN(price), MAX(price) FROM products;',
          pitfalls: ['想順便看 name → 會報錯 must appear in the GROUP BY clause。聚合完只剩一個數字，沒有「哪一個 name」。'],
        },
        {
          task: "SELECT COUNT(*) FROM users WHERE created_at::date = '2026-08-01';",
          hint: '::date 把「日期＋時間」切成只剩日期，才能跟 \'2026-08-01\' 比。',
          expect: '1 列：count = 2（Alice、Bob 是 8/1 建立的）。',
          answer: "SELECT COUNT(*) FROM users WHERE created_at::date = '2026-08-01';",
        },
      ],
      project: {
        task: '寫一句「pet_id = 1 這隻寵物的平均體重」。',
        hint: 'AVG(weight_kg) 加 WHERE pet_id = 1。',
        expect: '一句 SQL：SELECT AVG(weight_kg) FROM weight_logs WHERE pet_id = 1;',
        answer: 'SELECT AVG(weight_kg) FROM weight_logs WHERE pet_id = 1;',
      },
      teachKeys: ['聚合 = 很多列變一個數字', 'COUNT／SUM／AVG／MIN／MAX', 'NULL 不會被算進去'],
    },
  ],
}

export const world1Boss: Record<number, Exercise> = {
  1: {
    task: '建立 owners 表（id、name、email、city），INSERT 你自己，UPDATE 你的 city，最後 SELECT 出來。',
    hint: '四句：CREATE TABLE → INSERT → UPDATE … WHERE → SELECT。每句都要分號。',
    expect: 'CREATE TABLE、INSERT 0 1、UPDATE 1，最後 SELECT 出 1 列是你自己，city 是改過的那個。',
    answer:
      "CREATE TABLE owners (id SERIAL PRIMARY KEY, name VARCHAR(50) NOT NULL, email VARCHAR(100) UNIQUE, city VARCHAR(50));\nINSERT INTO owners (name, email, city) VALUES ('Sasha', 'sasha@example.com', 'Taipei');\nUPDATE owners SET city = 'Taoyuan' WHERE id = 1;\nSELECT * FROM owners;",
    pitfalls: ['UPDATE 沒有 WHERE：這次只有一列所以看不出來，但要養成習慣。'],
  },
  2: {
    task: "一句 SQL 查出 2026-08-01 建立的商品有幾個、平均價格、最高價格。",
    hint: 'COUNT(*)、AVG(price)、MAX(price) 三個放一起，WHERE 用 created_at::date。',
    expect: '1 列：count = 10、avg = 3460.0000…、max = 6800.00（10 個商品全是 8/1 建的）。',
    answer: "SELECT COUNT(*), AVG(price), MAX(price) FROM products WHERE created_at::date = '2026-08-01';",
  },
}
