import type { Exercise, Lesson } from '../../types'

/** 世界 2「多張表」：關 3、4、5。expect 用 seed 實跑結果。 */
export const world2: Record<number, Lesson[]> = {
  3: [
    {
      id: '3-1',
      title: 'GROUP BY',
      focus: 'GROUP BY 把同類收成一組，每組算一個數',
      check: '算出每位使用者各有幾張訂單',
      concept: '把同一類的列收成一組，每組算一個數字。SELECT 裡沒被聚合的欄要出現在 GROUP BY。',
      explain: [
        'GROUP BY 欄｜分組：把「同一個值」的列收成一籃，每籃算一個數。',
        '比喻：訂單依 user_id 分籃，每籃 COUNT(*) 就是「這個人有幾張訂單」。',
        '規則：SELECT 裡出現的欄，要嘛在 GROUP BY 裡，要嘛被聚合函數包住。',
        'AS｜別名：COUNT(*) AS order_count，結果欄名比較好讀。',
        '怎麼畫：畫幾個籃子，籃子上寫 user_id，籃子裡丟訂單，籃子下面寫數字。',
      ],
      cards: [25, 28],
      exercises: [
        {
          task: 'SELECT user_id, COUNT(*) AS order_count FROM orders GROUP BY user_id;',
          hint: 'SELECT 的 user_id 也要出現在 GROUP BY。',
          expect: '7 列（有下單的 7 個人）。user_id 1 → 2 張，其他人各 1 張。順序可能不固定，加 ORDER BY user_id 會整齊。',
          answer: 'SELECT user_id, COUNT(*) AS order_count FROM orders GROUP BY user_id ORDER BY user_id;',
          pitfalls: ['漏 GROUP BY → column "orders.user_id" must appear in the GROUP BY clause。'],
        },
        {
          task: 'SELECT user_id, SUM(total_amount) AS total FROM orders GROUP BY user_id;',
          hint: '把 COUNT(*) 換成 SUM(total_amount) 就好。',
          expect: '7 列。user_id 1 → 13100.00、2 → 3200.00、3 → 5400.00、4 → 6800.00、5 → 2100.00、6 → 4500.00、7 → 8400.00。',
          answer: 'SELECT user_id, SUM(total_amount) AS total FROM orders GROUP BY user_id ORDER BY user_id;',
        },
        {
          task: 'SELECT category_id, COUNT(*) FROM products GROUP BY category_id;',
          hint: '換一張表、換一個分組欄，模式一樣。',
          expect: '4 列：category 1 → 3、2 → 3、3 → 2、4 → 2。',
          answer: 'SELECT category_id, COUNT(*) FROM products GROUP BY category_id ORDER BY category_id;',
        },
      ],
      project: {
        task: '寫一句「每隻寵物有幾筆體重紀錄」（weight_logs 表，GROUP BY pet_id）。',
        hint: '照第 1 題的模式：把 orders 換成 weight_logs、user_id 換成 pet_id。',
        expect: 'SELECT pet_id, COUNT(*) … FROM weight_logs GROUP BY pet_id;',
        answer: 'SELECT pet_id, COUNT(*) AS log_count FROM weight_logs GROUP BY pet_id;',
      },
      teachKeys: ['GROUP BY 把同值的列收成一籃', '每籃用聚合算一個數', 'SELECT 的欄要在 GROUP BY 裡'],
    },
    {
      id: '3-2',
      title: 'HAVING 與 WHERE 的差別',
      focus: 'HAVING 是「分組之後」的篩選；WHERE 是「分組之前」',
      check: '篩出總消費 > 5000 的使用者',
      concept: 'WHERE 在分組前過濾「列」，HAVING 在分組後過濾「組」。',
      explain: [
        'WHERE｜分組前：先把不要的「單列」丟掉，再分籃。',
        'HAVING｜分組後：籃子算完數字，再把不合格的「整籃」丟掉。',
        '判斷法：條件裡有 COUNT／SUM／AVG 這種算出來的數字 → 一定是 HAVING。',
        '順序固定：WHERE → GROUP BY → HAVING → ORDER BY。',
        '怎麼畫：兩個漏斗，一個在籃子前面（WHERE），一個在籃子後面（HAVING）。',
      ],
      cards: [26, 27],
      exercises: [
        {
          task: 'SELECT user_id, SUM(total_amount) FROM orders GROUP BY user_id HAVING SUM(total_amount) > 5000;',
          hint: 'HAVING 裡要重寫一次 SUM(total_amount)，不能用別名。',
          expect: '4 列：user_id 1（13100）、3（5400）、4（6800）、7（8400）。',
          answer: 'SELECT user_id, SUM(total_amount) FROM orders GROUP BY user_id HAVING SUM(total_amount) > 5000;',
          pitfalls: ['寫成 WHERE SUM(total_amount) > 5000 → aggregate functions are not allowed in WHERE。'],
        },
        {
          task: 'SELECT user_id, COUNT(*) FROM orders GROUP BY user_id HAVING COUNT(*) >= 2;',
          hint: '找「訂單數 ≥ 2」的人。',
          expect: '1 列：user_id 1，count 2（只有 Alice 下過兩張）。',
          answer: 'SELECT user_id, COUNT(*) FROM orders GROUP BY user_id HAVING COUNT(*) >= 2;',
        },
        {
          task: "SELECT user_id, COUNT(*) FROM orders WHERE status = 'paid' GROUP BY user_id HAVING COUNT(*) >= 1;",
          hint: 'WHERE 先只留 paid 的單列，再分籃，再 HAVING。',
          expect: '5 列：user_id 1、2、3、5、7 各 1 張（Alice 的 shipped 那張被 WHERE 濾掉了）。',
          answer: "SELECT user_id, COUNT(*) FROM orders WHERE status = 'paid' GROUP BY user_id HAVING COUNT(*) >= 1;",
        },
      ],
      project: {
        task: '寫一句「體重紀錄 ≥ 3 筆的寵物」。',
        hint: '上一課的 GROUP BY pet_id 加上 HAVING COUNT(*) >= 3。',
        expect: 'SELECT pet_id, COUNT(*) FROM weight_logs GROUP BY pet_id HAVING COUNT(*) >= 3;',
        answer: 'SELECT pet_id, COUNT(*) FROM weight_logs GROUP BY pet_id HAVING COUNT(*) >= 3;',
      },
      teachKeys: ['WHERE 分組前濾列', 'HAVING 分組後濾組', '條件裡有聚合就用 HAVING'],
    },
  ],
  4: [
    {
      id: '4-1',
      title: 'FK 與一對多',
      focus: 'FK 是表與表之間的線；「多」的那邊放 FK',
      check: '指出 orders 裡哪一欄是 FK、指向哪張表',
      concept: 'FK 是指向另一張表 PK 的欄位。「一個使用者有很多訂單」→ orders 放 user_id。',
      explain: [
        'Foreign Key（FK）｜外鍵：一個欄位，裡面放的是「另一張表的 PK」。它就是兩張表之間的那條線。',
        'One-to-Many（1:N）｜一對多：一個使用者有很多訂單。',
        '口訣：FK 放在「多」的那邊。訂單很多 → orders 表放 user_id。',
        'ON｜配對條件：之後 JOIN 時，就是寫「orders.user_id = users.id」。',
        '怎麼畫：users ──< orders，一端寫 1、叉子端寫多；在 orders 的 user_id 旁邊寫 FK。',
      ],
      cards: [29, 30, 33],
      exercises: [
        {
          task: 'SELECT id, user_id FROM orders;   對照 users 表，user_id = 1 是誰？',
          hint: 'user_id 的數字去 users 表找 id 一樣的那列。',
          expect: '8 列。user_id 出現 1、2、1、3、4、5、6、7。user_id = 1 是 Alice Chen。',
          answer: 'SELECT id, user_id FROM orders;   → user_id 1 = Alice Chen',
        },
        {
          task: '在筆記本畫 users ──< orders，線的兩端寫 1 和 多，並在 orders 的 user_id 旁寫 FK。',
          hint: '叉子（鳥爪）畫在 orders 那邊。',
          expect: '兩個方框、一條線、1 在 users 端、叉子在 orders 端、user_id 標 FK。',
          answer: 'users(id PK) 1 ──< 多 orders(id PK, user_id FK → users.id)',
        },
        {
          task: 'SELECT * FROM orders WHERE user_id = 1;',
          hint: '用 FK 當條件，就是「找這個人的所有訂單」。',
          expect: '2 列：id 1（paid，7400.00）、id 3（shipped，5700.00）。',
          answer: 'SELECT * FROM orders WHERE user_id = 1;',
        },
      ],
      project: {
        task: '畫 owners ──< pets ──< weight_logs，並寫出每張表的 FK 欄名。',
        hint: '一個飼主很多寵物、一隻寵物很多體重紀錄。FK 都放在「多」那邊。',
        expect: '三個方框兩條線；pets 有 owner_id FK，weight_logs 有 pet_id FK。',
        answer: 'owners(id) 1──< pets(id, owner_id FK) 1──< weight_logs(id, pet_id FK)',
      },
      teachKeys: ['FK 是指向別表 PK 的欄', 'FK 放在多的那邊', 'FK 就是兩張表之間的線'],
    },
    {
      id: '4-2',
      title: 'INNER JOIN',
      focus: 'JOIN … ON 把兩張表對起來',
      check: '查出「每張訂單 + 下單者名字」',
      concept: '用 ON 把 FK 和 PK 對起來，兩邊都配得到才保留。',
      explain: [
        'INNER JOIN｜內部連接：把兩張表沿著 FK = PK 那條線「拼」起來，只留兩邊都配得到的列。',
        '寫法：FROM orders o JOIN users u ON o.user_id = u.id。o、u 是表的別名（短名字）。',
        '欄位前面加「誰的」：u.name、o.total_amount。兩張表都有 id、name 時一定要加。',
        '可以連著 JOIN 三、四張表，每多一張就多一個 JOIN … ON。',
        '怎麼畫：兩張表並排，用線把 user_id 和 id 連起來，右邊畫拼好的新表。',
      ],
      cards: [31],
      exercises: [
        {
          task: 'SELECT o.id, u.name, o.total_amount FROM orders o JOIN users u ON o.user_id = u.id;',
          hint: 'ON 後面是「FK = PK」：o.user_id = u.id。',
          expect: '8 列：1 Alice Chen 7400、2 Bob Lin 3200、3 Alice Chen 5700、4 Carol Wang 5400、5 David Liu 6800、6 Eve Huang 2100、7 Frank Wu 4500、8 Grace Tsai 8400。',
          answer: 'SELECT o.id, u.name, o.total_amount FROM orders o JOIN users u ON o.user_id = u.id;',
          pitfalls: ['column reference "id" is ambiguous → id 前面要寫 o. 或 u.。'],
        },
        {
          task: 'SELECT oi.order_id, p.name, oi.quantity FROM order_items oi JOIN products p ON oi.product_id = p.id;',
          hint: '這次 FK 是 order_items.product_id，PK 是 products.id。',
          expect: '16 列。order 1：Full Face Helmet A1 ×1、Bluetooth Headset B1 ×1；order 4 有 3 列，其中 Rain Gloves G2 ×2。',
          answer: 'SELECT oi.order_id, p.name, oi.quantity FROM order_items oi JOIN products p ON oi.product_id = p.id;',
        },
        {
          task: 'SELECT o.id, u.name, p.name FROM orders o JOIN users u ON o.user_id = u.id JOIN order_items oi ON oi.order_id = o.id JOIN products p ON p.id = oi.product_id;',
          hint: '三個 JOIN，每個 ON 寫一條線。慢慢打，一行一個 JOIN。',
          expect: '16 列，每列是「訂單 id、買家、商品」。order 1 兩列都是 Alice Chen；結果兩欄都叫 name（可用 AS 改名）。',
          answer: 'SELECT o.id, u.name AS buyer, p.name AS product FROM orders o JOIN users u ON o.user_id = u.id JOIN order_items oi ON oi.order_id = o.id JOIN products p ON p.id = oi.product_id;',
        },
      ],
      project: {
        task: '寫一句「每筆體重紀錄 + 寵物名字」（weight_logs JOIN pets）。',
        hint: 'FROM weight_logs w JOIN pets p ON w.pet_id = p.id。',
        expect: 'SELECT p.name, w.weight_kg, w.measured_at FROM weight_logs w JOIN pets p ON w.pet_id = p.id;',
        answer: 'SELECT p.name, w.weight_kg, w.measured_at FROM weight_logs w JOIN pets p ON w.pet_id = p.id;',
      },
      teachKeys: ['JOIN 把兩張表沿 FK=PK 拼起來', 'ON 寫配對條件', 'INNER 只留兩邊都配到的'],
    },
    {
      id: '4-3',
      title: 'LEFT JOIN 與 NULL',
      focus: 'LEFT JOIN 會保留左邊全部，配不到的補 NULL',
      check: '找出沒下過單的使用者',
      concept: '左表全留，右邊沒配到補 NULL。這就是找「沒有」的方法。多對多要靠中間表。',
      explain: [
        'LEFT JOIN｜左連接：左邊那張表（FROM 後面的）每一列都留著，右邊配不到就補 NULL。',
        '用途：找「沒有」的。沒下過單的人，右邊 orders 全是 NULL → WHERE o.id IS NULL。',
        'INNER JOIN 會把沒訂單的人直接丟掉，所以找不到「沒有」。',
        'Many-to-Many（N:M）｜多對多：一張訂單有很多商品、一個商品在很多訂單 → 中間放 order_items，兩邊 FK 都在它身上。',
        '怎麼畫：左表全部列都畫出來，右邊配不到的格子寫 NULL。',
      ],
      cards: [32, 34],
      exercises: [
        {
          task: 'SELECT u.name, o.id FROM users u LEFT JOIN orders o ON o.user_id = u.id;',
          hint: '跟 INNER JOIN 只差一個字 LEFT。',
          expect: '11 列（10 人，Alice 兩張單佔 2 列）。Henry Kuo、Ivy Hsu、Jack Peng 的 id 是空白（NULL）。',
          answer: 'SELECT u.name, o.id FROM users u LEFT JOIN orders o ON o.user_id = u.id;',
        },
        {
          task: 'SELECT u.name FROM users u LEFT JOIN orders o ON o.user_id = u.id WHERE o.id IS NULL;',
          hint: '在上一句後面加 WHERE o.id IS NULL（不是 = NULL）。',
          expect: '3 列：Henry Kuo、Ivy Hsu、Jack Peng（順序可能不同）。',
          answer: 'SELECT u.name FROM users u LEFT JOIN orders o ON o.user_id = u.id WHERE o.id IS NULL;',
          pitfalls: ['WHERE o.id = NULL → 0 列。NULL 只能用 IS NULL 判斷。'],
        },
        {
          task: '在筆記本畫 orders ──< order_items >── products，說出為什麼需要 order_items。',
          hint: '一張單很多商品；一個商品出現在很多單。兩邊都是「多」。',
          expect: '三個方框，中間 order_items 兩邊都是叉子；一句話：「兩邊都是多，FK 沒地方放，所以中間加一張表放兩個 FK」。',
          answer: 'orders 1──< order_items(order_id FK, product_id FK) >──1 products。多對多沒辦法在任一邊放單一 FK，所以要中間表。',
        },
      ],
      project: {
        task: '寫一句「所有寵物，含沒有體重紀錄的」（pets LEFT JOIN weight_logs）。',
        hint: 'pets 要全留，所以 pets 放左邊（FROM pets）。',
        expect: 'SELECT p.name, w.weight_kg FROM pets p LEFT JOIN weight_logs w ON w.pet_id = p.id;',
        answer: 'SELECT p.name, w.weight_kg FROM pets p LEFT JOIN weight_logs w ON w.pet_id = p.id;',
      },
      teachKeys: ['LEFT JOIN 左表全留', '配不到補 NULL，用 IS NULL 找「沒有」', '多對多要中間表'],
    },
  ],
  5: [
    {
      id: '5-1',
      title: 'IN 子查詢與比較子查詢',
      focus: '括號裡先跑一個小查詢，結果給外面用',
      check: '查出金額高於平均的訂單',
      concept: '括號裡先跑小查詢，結果給外面用。',
      explain: [
        'Subquery｜子查詢：括號裡一句完整的 SELECT，先跑它，結果交給外面那句用。',
        'IN (子查詢)｜在名單裡：子查詢回一串值（一欄多列），外面用 IN 對。',
        '比較子查詢：子查詢只回一個數字（例如 AVG），外面用 > < = 比。',
        '讀法：先讀括號裡的，把它想成一個「暫時的名單／數字」，再讀外面。',
        '怎麼畫：畫一個大框，裡面一個小框；小框先算，箭頭指到大框的 WHERE。',
      ],
      cards: [35, 36],
      exercises: [
        {
          task: 'SELECT name FROM users WHERE id IN (SELECT user_id FROM orders);',
          hint: '括號裡先跑：所有下過單的 user_id 名單。',
          expect: '7 列：Alice Chen、Bob Lin、Carol Wang、David Liu、Eve Huang、Frank Wu、Grace Tsai。',
          answer: 'SELECT name FROM users WHERE id IN (SELECT user_id FROM orders);',
        },
        {
          task: 'SELECT * FROM orders WHERE total_amount > (SELECT AVG(total_amount) FROM orders);',
          hint: '括號裡算出平均 5437.5，外面找比它大的。',
          expect: '4 列：id 1（7400）、3（5700）、5（6800）、8（8400）。',
          answer: 'SELECT * FROM orders WHERE total_amount > (SELECT AVG(total_amount) FROM orders);',
          pitfalls: ['直接寫 WHERE total_amount > AVG(total_amount) → aggregate functions are not allowed in WHERE。要包成子查詢。'],
        },
        {
          task: "SELECT name FROM products WHERE category_id IN (SELECT id FROM categories WHERE name = 'Helmets');",
          hint: '括號裡先找出 Helmets 這個分類的 id（是 1）。',
          expect: '3 列：Full Face Helmet A1、Modular Helmet M2、Open Face Helmet O3。',
          answer: "SELECT name FROM products WHERE category_id IN (SELECT id FROM categories WHERE name = 'Helmets');",
        },
      ],
      project: {
        task: '假設 medical_history 表有 pet_id。寫一句「有病歷的寵物」。',
        hint: '子查詢回「有病歷的 pet_id 名單」，外面 pets WHERE id IN (…)。',
        expect: 'SELECT name FROM pets WHERE id IN (SELECT pet_id FROM medical_history);',
        answer: 'SELECT name FROM pets WHERE id IN (SELECT pet_id FROM medical_history);',
      },
      teachKeys: ['括號裡先跑', 'IN 對名單', '> < 比一個數字'],
    },
    {
      id: '5-2',
      title: '找「沒有」的三種寫法',
      focus: '找「沒有」的三種寫法，結果一樣',
      check: '用兩種寫法找出從未下單的使用者',
      concept: 'NOT IN、NOT EXISTS、LEFT JOIN … IS NULL 結果一樣，讀起來不同。要欄位就用 JOIN。',
      explain: [
        '三種找「沒有」：① NOT IN (子查詢) ② NOT EXISTS (子查詢) ③ LEFT JOIN … WHERE 右邊.id IS NULL。',
        '① 最好讀；② 子查詢裡可以引用外面的表（o.user_id = u.id）；③ 可以順便拿右表的欄位。',
        'Subquery vs JOIN｜何時用哪個：只要「有沒有」→ 子查詢；要拿另一張表的欄 → JOIN。',
        '⚠ NOT IN 遇到子查詢裡有 NULL 會整個回空；orders.user_id 是 NOT NULL 所以這裡安全。',
        '怎麼畫：三條路通到同一個終點「Henry、Ivy、Jack」。',
      ],
      cards: [37, 38],
      exercises: [
        {
          task: 'SELECT name FROM users WHERE id NOT IN (SELECT user_id FROM orders);',
          hint: '上一課的 IN 前面加 NOT。',
          expect: '3 列：Henry Kuo、Ivy Hsu、Jack Peng。',
          answer: 'SELECT name FROM users WHERE id NOT IN (SELECT user_id FROM orders);',
        },
        {
          task: 'SELECT name FROM users u WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.user_id = u.id);',
          hint: 'SELECT 1 只是「有沒有」，不在意內容。o.user_id = u.id 把裡外接起來。',
          expect: '同樣 3 列：Henry Kuo、Ivy Hsu、Jack Peng（順序可能不同）。',
          answer: 'SELECT name FROM users u WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.user_id = u.id);',
        },
        {
          task: 'SELECT u.name FROM users u LEFT JOIN orders o ON o.user_id = u.id WHERE o.id IS NULL;',
          hint: '關 4 學過的那句。',
          expect: '同樣 3 列。三句結果一樣就對了。',
          answer: 'SELECT u.name FROM users u LEFT JOIN orders o ON o.user_id = u.id WHERE o.id IS NULL;',
        },
      ],
      project: {
        task: '用三種寫法各寫一句「從未量過體重的寵物」。',
        hint: 'users→pets、orders→weight_logs、user_id→pet_id，三句直接代換。',
        expect: '三句 SQL，分別有 NOT IN、NOT EXISTS、LEFT JOIN … IS NULL。',
        answer:
          'SELECT name FROM pets WHERE id NOT IN (SELECT pet_id FROM weight_logs);\nSELECT name FROM pets p WHERE NOT EXISTS (SELECT 1 FROM weight_logs w WHERE w.pet_id = p.id);\nSELECT p.name FROM pets p LEFT JOIN weight_logs w ON w.pet_id = p.id WHERE w.id IS NULL;',
      },
      teachKeys: ['NOT IN／NOT EXISTS／LEFT JOIN IS NULL', '三種結果一樣', '要欄位就用 JOIN'],
    },
  ],
}

export const world2Boss: Record<number, Exercise> = {
  3: {
    task: '每個城市有幾位使用者？只列出 ≥ 2 人的城市。',
    hint: 'GROUP BY city，然後 HAVING COUNT(*) >= 2。',
    expect: '3 列：Taipei 2、Taichung 2、Taoyuan 2（順序可能不同）。',
    answer: 'SELECT city, COUNT(*) FROM users GROUP BY city HAVING COUNT(*) >= 2;',
  },
  4: {
    task: '每位使用者的名字 + 訂單數，沒下單的人也要出現（顯示 0）。',
    hint: 'users LEFT JOIN orders，然後 GROUP BY u.id, u.name，COUNT 要數 o.id（不是 *），沒單的才會是 0。',
    expect: '10 列。Alice Chen 2、其他有單的 1、Henry Kuo／Ivy Hsu／Jack Peng 是 0。',
    answer: 'SELECT u.name, COUNT(o.id) AS order_count FROM users u LEFT JOIN orders o ON o.user_id = u.id GROUP BY u.id, u.name ORDER BY u.id;',
    pitfalls: ['COUNT(*) 會讓沒單的人變 1（因為 LEFT JOIN 補了一列 NULL）。要 COUNT(o.id)。'],
  },
  5: {
    task: '找出高於平均訂單金額的訂單，並顯示下單者名字（子查詢 + JOIN）。',
    hint: '關 5-1 第 2 題那句，再 JOIN users 拿名字。',
    expect: '4 列：1 Alice Chen 7400、3 Alice Chen 5700、5 David Liu 6800、8 Grace Tsai 8400。',
    answer: 'SELECT o.id, u.name, o.total_amount FROM orders o JOIN users u ON u.id = o.user_id WHERE o.total_amount > (SELECT AVG(total_amount) FROM orders);',
  },
}
